### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by santiperone** [importables/importable#2]
I tried this out and I'm getting 
![image](https://github.com/importables/importable/assets/69366194/1160afa1-0184-4797-91e5-bbd19de3bd17)
Is there any particular setup i need for this to run?
Sounds really interesting being able to get typing in yaml files!

**Comment by jonathantneal** [comment]
Yes, that looks good. Have you checked if VS Code is using the workspace version of TypeScript?

I’ve added a section to address this at https://github.com/importables/importable#faq
